platform :ios, '8.0'
use_frameworks!

target 'MobiUwb' do
    pod 'SlideMenuControllerSwift', '~> 2.0'
    pod 'SwiftyJSON', '~> 2.3'
    pod 'SWXMLHash', '~> 2.0'
end

target 'MobiUwbTests' do

end

